### ISSUE TITLE
Unicode, please

### ISSUE THREAD

**Issue by polkovnikov-ph** [normalize/autoinstall#7]
First usage on Node 0.12, Windows 7. Cyrillic user name makes `autoinstall` go bananas.

	>a index.js
	module.js:338
		throw err;
			  ^
	Error: Cannot find module 'C:Users¦Э¦¦ ¦Ч¦-TПAppDataRoamingpmode_modulesautoinstallindex.js'
		at Function.Module._resolveFilename (module.js:336:15)
		at Function.Module._load (module.js:278:25)
		at Module.require (module.js:365:17)
		at require (module.js:384:17)
		at [eval]:1:1
		at Object.exports.runInThisContext (vm.js:74:17)
		at Object.<anonymous> ([eval]-wrapper:6:22)
		at Module._compile (module.js:460:26)
		at evalScript (node.js:431:25)
		at startup (node.js:90:7)

I'm unsure if it's a bug in `autoinstall` or some imperfections in Node.js internals you're using. Though I can't imagine a way backslashes disappeared from the path.

**Comment by jonathanong** [comment]
I have no idea what to do here...

**Comment by polkovnikov-ph** [comment]
@jonathanong I've looked through the source, and there's no place where there could be a bug in library code. Could you assist in creating the issue on `node`'s github? I have no idea how to localize the bug either.

**Comment by jonathanong** [comment]
you should create it! i don't know what to say! i think they do have issues with this in node. also, try iojs.
